spring.datasource.url=jdbc:postgresql://vyg-batch-2.cgtfswn9milw.ap-south-1.rds.amazonaws.com:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=vygchatai
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update


spring.jpa.open-in-view=false

# Multi-tenancy
spring.security.oauth2.resourceserver.multitenant.enabled=true
spring.security.oauth2.resourceserver.multitenant.resolve-mode=header
spring.security.oauth2.resourceserver.multitenant.header.header-name=X-TENANT-ID

# logging.level.org.springframework=DEBUG
# logging.level.org.hibernate=DEBUG
	
spring.h2.console.enabled=true
# spring.h2.console.path=/h2-console    
server.port=8081

spring.security.oauth2.resourceserver.jwt.issuer-uri=https://user.evyoog.com/realms/eVyoog
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=https://user.evyoog.com/realms/eVyoog/protocol/openid-connect/certs